### ISSUE TITLE
esm bundle not ES5

### ISSUE THREAD

**Issue by TkDodo** [libre-org/atom#15]
It seems like the bundled `index.esm.js` ist not valid `ES5`, but `ES6`. Can you confirm that? If so, would it be possible to switch to `ES5` instead?

I attached the file from my `node_modules` directory. As you can see, it uses template literals and arrow functions, which are not valid ES5.

[index.esm.js.zip](https://github.com/libre-org/atom/files/3712467/index.esm.js.zip)

**Comment by derrickbeining** [comment]
@TkDodo sorry about that. Hopefully it's as simple as changing [this one line](https://github.com/libre-org/atom/blob/15aca7cc55a63c97d202aabfe43fb3062a19a8bf/rollup.config.ts#L11) in the rollup config. I'll take care of it in the next few days.

**Comment by TkDodo** [comment]
Thanks for fixing this, I appreciate it 🎉
